name = "cakesbyvarsha-api"
main = "api/worker.js"
compatibility_date = "2023-10-30"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "cakesbyvarsha-db"
database_id = "your-database-id-here"

# R2 Storage binding for images
[[r2_buckets]]
binding = "IMAGES"
bucket_name = "cakesbyvarsha-images"

# Environment variables (secrets will be set via Cloudflare dashboard)
[vars]
ENVIRONMENT = "production"
